In [1]:
import numpy as np
import pandas as pd

## Datatypes && attributes

In [2]:
# Numpy's main datatype is ndarray
# ndarray = n-dimension array
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])

a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
               [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])

In [5]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [6]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [7]:
# shape of an array
a1.shape

(3,)

In [8]:
a2.shape

(2, 3)

In [9]:
a3.shape

(2, 3, 3)

In [10]:
# dimension of an array
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [11]:
# for having data type within an array
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [12]:
# counting elements within an array
a1.size, a2.size, a3.size

(3, 6, 18)

In [13]:
# create a DataFrame from a numpy array
df = pd.DataFrame(a2)

In [14]:
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## Creating Arrays

In [15]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [16]:
# An array of ones
ones = np.ones((2, 3))

In [17]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
# An array of zeros
zeros = np.zeros((2, 3))

In [19]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [24]:
# An array from a range
range_array = np.arange(0, 10, 2)

In [25]:
range_array

array([0, 2, 4, 6, 8])

# Arrays filled with random values

In [28]:
# An array filled with random values and a given size
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[0, 0, 5, 5, 0],
       [3, 7, 6, 3, 2],
       [5, 7, 2, 1, 1]])

In [30]:
# An array filled with random values in [0.0, 1.0[ interval
random_array_2 = np.random.random((5, 3))
random_array_2

array([[0.25086011, 0.7394545 , 0.53863543],
       [0.11649879, 0.8115997 , 0.25618312],
       [0.55108228, 0.7739411 , 0.83957534],
       [0.972966  , 0.87915447, 0.63579503],
       [0.15454266, 0.77520734, 0.06732923]])

## The random seed

In [33]:
# Pseudo-random numbers
# The random seed makes generated numbers aligned with the seed
# If the seed is given a value then everytime the same values will be generated
np.random.seed(seed=0)
random_array_3 = np.random.randint(10, size=(5, 3))
random_array_3

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

# Viewing arrays and matrices

In [36]:
# Retrieving unique values with the unique function
np.unique(random_array_3, axis=1)

array([[0, 3, 5],
       [7, 9, 3],
       [5, 2, 3],
       [7, 6, 4],
       [8, 1, 8]])

In [37]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [38]:
# Indexing 2D array
a2[0]

array([1. , 2. , 3.3])

In [39]:
# Value at position (i,j) => array[i,j]
a2[0, 1]

2.0

In [40]:
# Indexing in a 3D array
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [47]:
a3.shape

(2, 3, 3)

In [42]:
# Returns the first matrix
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
# Slicing
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [53]:
# A 4D array
a4 = np.random.randint(10, size=(2, 3, 4, 5))
a4

array([[[[6, 7, 7, 8, 1],
         [5, 9, 8, 9, 4],
         [3, 0, 3, 5, 0],
         [2, 3, 8, 1, 3]],

        [[3, 3, 7, 0, 1],
         [9, 9, 0, 4, 7],
         [3, 2, 7, 2, 0],
         [0, 4, 5, 5, 6]],

        [[8, 4, 1, 4, 9],
         [8, 1, 1, 7, 9],
         [9, 3, 6, 7, 2],
         [0, 3, 5, 9, 4]]],


       [[[4, 6, 4, 4, 3],
         [4, 4, 8, 4, 3],
         [7, 5, 5, 0, 1],
         [5, 9, 3, 0, 5]],

        [[0, 1, 2, 4, 2],
         [0, 3, 2, 0, 7],
         [5, 9, 0, 2, 7],
         [2, 9, 2, 3, 3]],

        [[2, 3, 4, 1, 2],
         [9, 1, 4, 6, 8],
         [2, 3, 0, 0, 6],
         [0, 6, 3, 3, 8]]]])

In [54]:
a4.shape

(2, 3, 4, 5)

In [55]:
# Get the 4 first numbers of the inner most arrays
a4[:,:,:,:4]

array([[[[6, 7, 7, 8],
         [5, 9, 8, 9],
         [3, 0, 3, 5],
         [2, 3, 8, 1]],

        [[3, 3, 7, 0],
         [9, 9, 0, 4],
         [3, 2, 7, 2],
         [0, 4, 5, 5]],

        [[8, 4, 1, 4],
         [8, 1, 1, 7],
         [9, 3, 6, 7],
         [0, 3, 5, 9]]],


       [[[4, 6, 4, 4],
         [4, 4, 8, 4],
         [7, 5, 5, 0],
         [5, 9, 3, 0]],

        [[0, 1, 2, 4],
         [0, 3, 2, 0],
         [5, 9, 0, 2],
         [2, 9, 2, 3]],

        [[2, 3, 4, 1],
         [9, 1, 4, 6],
         [2, 3, 0, 0],
         [0, 6, 3, 3]]]])